[build]
  base = "react-app"          # The directory where Netlify should run the build command
  publish = "react-app/build" # The directory where the build output is located
  command = "npm run build"   # The build command to run

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
